/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.train.packs;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class AddTicket extends javax.swing.JFrame {

    /**
     * Creates new form AddTicket
     */
    String name;
    public AddTicket(String uname) {
        initComponents();
        name=uname;
       updatecmmbox();
                   if(name.equals("jubli"))
        {
      
        }
            else {
             jComboBox1.setVisible(false);
        jLabel10.setVisible(false);
        jButton3.setVisible(false);
        jSpinField1.setVisible(false);
        jButton5.setVisible(false);
        jLabel7.setVisible(false);
        jButton1.setVisible(false);
        jLabel3.setVisible(false);
        jTextField1.setVisible(false);

 
            }
        
    }

    private AddTicket() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    

    
    public void updatecmmbox()
    {
        
        try
        {        
            
            String sql="SELECT * FROM tschedule";
            Connection con=  SConnection.getcon();
            PreparedStatement pst = con.prepareStatement (sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) 
            {
              jComboBox1.addItem(rs.getString("schedule_id"));
            }                       

        }
    
    catch (Exception e)
    {
        System.out.println("Error: "+e);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jSpinField1 = new com.toedter.components.JSpinField();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarea = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setText("Seat No:");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setText("Passenger ID:");

        jButton2.setBackground(new java.awt.Color(60, 63, 65));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton2.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jButton2.setText("BACK");
        jButton2.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(60, 63, 65));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jButton1.setText("ADD");
        jButton1.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Actions.Green"), 3, true));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setText("Schedule ID:");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TICKET COUNTER");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        jButton3.setText("View");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("View");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jSpinField1.setMinimum(0);

        jButton7.setBackground(new java.awt.Color(60, 63, 65));
        jButton7.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton7.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jButton7.setText("CANCEL");
        jButton7.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Actions.Red"), 3, true));
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/tik.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jComboBox1, 0, 232, Short.MAX_VALUE)
                                            .addComponent(jTextField1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton5)
                                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(jSpinField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(jLabel10)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 600));

        tarea.setEditable(false);
        tarea.setColumns(20);
        tarea.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        tarea.setRows(5);
        tarea.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)), "YOUR TICKET", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Gill Sans MT Condensed", 0, 18))); // NOI18N
        jScrollPane1.setViewportView(tarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 370, 440));

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 204, 204));
        jButton4.setText("PRINT");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 370, 50));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 280, 30));

        jButton6.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Search");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 30, 80, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/bg10.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(500, 600));
        jLabel4.setMinimumSize(new java.awt.Dimension(500, 600));
        jLabel4.setPreferredSize(new java.awt.Dimension(500, 600));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 490, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       if(name.equals("user"))
        {
        Menu  m =new Menu("user");
        m.setVisible(true);
        dispose();
        }
        else if(name.equals("jubli")){
        Menu  m =new Menu("jubli");
        m.setVisible(true);
        dispose();}
    }//GEN-LAST:event_jButton2ActionPerformed

         String tid;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        try{
            
            
            
        PreparedStatement ps;
        Connection con=  SConnection.getcon();
        
         ps=con.prepareStatement("Insert into ticket(schedule_id,passenger_id,seat_no) values(?,?,?)"); 
         ps.setString (1,jComboBox1.getSelectedItem().toString());
         ps.setString (2,jTextField1.getText().toString());
         ps.setString (3,""+jSpinField1.getValue());
         
         String sid=jComboBox1.getSelectedItem().toString();
         String pid=jTextField1.getText().toString();
         String sn=""+jSpinField1.getValue();
         ps.executeUpdate();
                   
         try
        {  
            String sql = "SELECT * FROM ticket t JOIN tschedule s ON t.schedule_id = s.schedule_id JOIN passenger p ON t.passenger_id = p.passenger_id JOIN train tr ON s.train_id = tr.train_id JOIN traintype tt ON tr.t_type = tt.type_id JOIN station dep ON s.departure_station = dep.station_id JOIN station arr ON s.arrival_station = arr.station_id WHERE ticket_id = (SELECT MAX(ticket_id) FROM ticket);";
            PreparedStatement pst = con.prepareStatement (sql);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next())
            {
                tarea.setText ("-------------------------------------------------\n");
                tarea.append ("\tD.M.C Railway Reservation\n");
                tarea.append ("-------------------------------------------------\n\n\n");
                tarea.append ("TICKET ID\t\t"+":"+rs.getString("ticket_id"));
                tarea.append ("\nPASSENGER NAME\t"+":"+""+rs.getString("first_name")+" "+rs.getString("last_name"));
                tarea.append ("\nFROM\t\t"+":"+rs.getString("dep.station_name"));
                tarea.append ("\nTO\t\t"+":"+rs.getString("arr.station_name"));
                tarea.append ("\nDEP TIME\t\t"+":"+rs.getString("departure_time"));
                tarea.append ("\nARR TIME\t\t"+":"+rs.getString("arrival_time"));
                
                tarea.append ("\nDATE\t\t"+":"+rs.getString("t_date"));
                tarea.append ("\nCLASS\t\t"+":"+rs.getString("type_name"));               
                tarea.append ("\n\n\n\n-------------------------------------------------");      
                tarea.append ("\nTOTAL PRICE\t\t\t"+": $"+rs.getString("type_price"));               
                tarea.append ("\n-------------------------------------------------");
               JOptionPane.showMessageDialog(null,"Ticket Generated Successfully...");
           
               
            }                 
         } 
  
       catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,""+e );       
        }
 

         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null,e);
         }
        
    
    
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
                PrinterJob pj = PrinterJob.getPrinterJob();

         pj.setJobName("Print Record");
        pj.setPrintable(new Printable(){
            @Override
            public int print(Graphics graphics, PageFormat pf,int pageIndex) throws PrinterException {
            if(pageIndex > 0){
                return Printable.NO_SUCH_PAGE;
            }
            Graphics2D graphics2d = (Graphics2D)graphics;
            graphics2d.translate(pf.getImageableX()*2,pf.getImageableY()*2);
           graphics2d.scale(1.5,1.5);
           tarea.paint(graphics2d);
           
           return Printable.PAGE_EXISTS;
            }
            });
        boolean result= pj.printDialog();
        if (result)
        {
            try
            {
                pj.print();
            
            }
            catch(PrinterException printerException)
            {
            JOptionPane.showMessageDialog(this, "Print Error: "+printerException.getMessage());
            }
        
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         AdminSchedule vdt = new AdminSchedule("popup");
        vdt.setVisible(true);
        vdt.pack();
        vdt.setLocationRelativeTo(null);
        vdt.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
              PassengerDetails vdt = new PassengerDetails("popup");
        vdt.setVisible(true);
        vdt.pack();
        vdt.setLocationRelativeTo(null);
        vdt.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
           String tno=jTextField2.getText();
           try
        {  
            String sql = "DELETE FROM ticket WHERE ticket_id = ?;";
            Connection con=  SConnection.getcon();
            PreparedStatement pst = con.prepareStatement (sql);
            pst.setString (1,tno);
            pst.executeUpdate();
            tarea.setText("");
         
         JOptionPane.showMessageDialog(this,"Ticket Cancelled");
                             
         } 
  
       catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Already Used" );       
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String tno=jTextField2.getText();
           try
        {  
            String sql = "SELECT * FROM ticket t JOIN tschedule s ON t.schedule_id = s.schedule_id JOIN passenger p ON t.passenger_id = p.passenger_id JOIN train tr ON s.train_id = tr.train_id JOIN traintype tt ON tr.t_type = tt.type_id JOIN station dep ON s.departure_station = dep.station_id JOIN station arr ON s.arrival_station = arr.station_id WHERE ticket_id = ?;";
            Connection con=  SConnection.getcon();
            PreparedStatement pst = con.prepareStatement (sql);
            pst.setString (1,tno);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next())
            {
                tarea.setText ("-------------------------------------------------\n");
                tarea.append ("\tD.M.C Railway Reservation\n");
                tarea.append ("-------------------------------------------------\n\n\n");
                tarea.append ("TICKET ID\t\t"+":"+rs.getString("ticket_id"));
                tarea.append ("\nPASSENGER NAME\t"+":"+""+rs.getString("first_name")+" "+rs.getString("last_name"));
                tarea.append ("\nFROM\t\t"+":"+rs.getString("dep.station_name"));
                tarea.append ("\nTO\t\t"+":"+rs.getString("arr.station_name"));
                tarea.append ("\nDEP TIME\t\t"+":"+rs.getString("departure_time"));
                tarea.append ("\nARR TIME\t\t"+":"+rs.getString("arrival_time"));
                
                tarea.append ("\nDATE\t\t"+":"+rs.getString("t_date"));
                tarea.append ("\nCLASS\t\t"+":"+rs.getString("type_name"));               
                tarea.append ("\n\n\n\n-------------------------------------------------");      
                tarea.append ("\nTOTAL PRICE\t\t\t"+": $"+rs.getString("type_price"));               
                tarea.append ("\n-------------------------------------------------");
               JOptionPane.showMessageDialog(null,"Ticket Generated Successfully...");
           
               
            }                 
         } 
  
       catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Ticket Doesn't exist" );       
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddTicket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddTicket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextArea tarea;
    // End of variables declaration//GEN-END:variables

    private void printRecord(JTextArea tarea) {
        PrinterJob pj = PrinterJob.getPrinterJob();
        
        pj.setJobName("Print Record");
        pj.setPrintable(new Printable(){
            @Override
            public int print(Graphics graphics, PageFormat pf,int pageIndex) throws PrinterException {
            if(pageIndex > 0){
                return Printable.NO_SUCH_PAGE;
            }
            Graphics2D graphics2d = (Graphics2D)graphics;
            graphics2d.translate(pf.getImageableX()*2,pf.getImageableY()*2);
           graphics2d.scale(0.5,0.5);
           tarea.paint(graphics2d);
           
           return Printable.PAGE_EXISTS;
            }
            });
        boolean result= pj.printDialog();
        if (result)
        {
            try
            {
                pj.print();
            
            }
            catch(PrinterException printerException)
            {
            JOptionPane.showMessageDialog(this, "Print Error: "+printerException.getMessage());
            }
        
        }
        
    }
}
