/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.train.packs;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Rectangle;
import java.awt.Robot;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;


import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author HP
 */
public class UserFeedback extends javax.swing.JFrame {

  

    /**
     * Creates new form DeleteTrain
     */
    String tname;
    public UserFeedback(String uname) {
        initComponents();
        tname=uname;
    }

    private UserFeedback() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        img = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        lead = new javax.swing.JLabel();
        pho = new javax.swing.JLabel();
        emal = new javax.swing.JLabel();
        lead1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        s4 = new javax.swing.JLabel();
        s5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/jubli.png"))); // NOI18N
        img.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 170, 200));

        name.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        name.setText("Soojal Kumar");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 230, -1));

        lead.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        lead.setForeground(new java.awt.Color(102, 102, 102));
        lead.setText("BackEnd Developer");
        getContentPane().add(lead, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 210, -1));

        pho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pho.setText("Phone : +923362747628");
        getContentPane().add(pho, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 220, -1));

        emal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        emal.setText("Email  : cs211024@dsu.com");
        getContentPane().add(emal, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 190, -1));

        lead1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        lead1.setForeground(new java.awt.Color(255, 204, 0));
        lead1.setText("Our Team");
        getContentPane().add(lead1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 210, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/Button Next.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 60, 50));

        jLabel1.setBackground(new java.awt.Color(220, 227, 237));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 470, 240));

        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Our project introduces railway reservation system with an objective to make the reservation system more efficient, easier and fast. This project explores how computer technology can be used to solve the problem of user. The main objectives provided by this software are as follows:\n  \nWe can enquire about availability of trains. We can reserve and cancel their seats This project is dedicated to model existing railway reservation systems that aim at development of Railway Reservation System that facilitates the railway customer to manage their reservations and the railway administrator to modify the backend database in a user-friendly manner.\n\nFor Further Enqruiries:\nEMAIL    :  arjun@mahabaarath.com\nPHONE   :  03362747628");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 490, 240));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 320, 10));

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator3.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, 310, 10));

        jSeparator4.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator4.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 10, 200));

        jSeparator5.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 480, 10));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 204, 0));
        jLabel7.setText("About Us");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 100, 50));

        jPanel1.setBackground(new java.awt.Color(224, 224, 224));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea2.setColumns(1);
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Please leave your feedback below:");

        s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png"))); // NOI18N
        s2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s2MouseClicked(evt);
            }
        });

        s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png"))); // NOI18N
        s1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s1MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("How was your experience?");

        s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png"))); // NOI18N
        s3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s3MouseClicked(evt);
            }
        });

        s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png"))); // NOI18N
        s4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s4MouseClicked(evt);
            }
        });

        s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png"))); // NOI18N
        s5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s5MouseClicked(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));

        jButton1.setBackground(new java.awt.Color(224, 224, 224));
        jButton1.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton1.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        jButton1.setText("SUBMIT");
        jButton1.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Actions.Green"), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(224, 224, 224));
        jButton2.setFont(new java.awt.Font("Tw Cen MT", 1, 18)); // NOI18N
        jButton2.setForeground(javax.swing.UIManager.getDefaults().getColor("Actions.Red"));
        jButton2.setText("BACK");
        jButton2.setBorder(new javax.swing.border.LineBorder(javax.swing.UIManager.getDefaults().getColor("Actions.Red"), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Feedback");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Enter Your Ticket ID :");

        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 1, true));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(s1)
                                    .addGap(10, 10, 10)
                                    .addComponent(s2)
                                    .addGap(10, 10, 10)
                                    .addComponent(s3)
                                    .addGap(10, 10, 10)
                                    .addComponent(s4)
                                    .addGap(10, 10, 10)
                                    .addComponent(s5))
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(29, 29, 29)
                                    .addComponent(jTextField1)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s1)
                    .addComponent(s2)
                    .addComponent(s3)
                    .addComponent(s4)
                    .addComponent(s5))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 460, 600));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int star=0;
    private void s1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s1MouseClicked
        // TODO add your handling code here:
            s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rss(1).png")));
            s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png")));
            s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png")));
            s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png")));
            s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png")));
            star=1;
    }//GEN-LAST:event_s1MouseClicked

    private void s2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s2MouseClicked
        // TODO add your handling code here:
            s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rss(1).png")));
            s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rss(1).png")));
            s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png")));
            s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png")));
            s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png")));
            star=2;

    }//GEN-LAST:event_s2MouseClicked

    private void s3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s3MouseClicked
        // TODO add your handling code here:
            s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rss(1).png")));
            s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rss(1).png")));
            s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rss(1).png")));
            s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png")));
            s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png")));
                        star=3;

    }//GEN-LAST:event_s3MouseClicked

    private void s4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s4MouseClicked
        // TODO add your handling code here:
                    star=4;

             s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rss(1).png")));
            s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rss(1).png")));
            s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rss(1).png")));
            s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rss(1).png")));
            s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png")));
    }//GEN-LAST:event_s4MouseClicked

    private void s5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s5MouseClicked
        // TODO add your handling code here:
                    star=5;

             s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rss(1).png")));
            s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rss(1).png")));
            s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rss(1).png")));
            s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rss(1).png")));
            s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rss(1).png")));
    }//GEN-LAST:event_s5MouseClicked
int pos=1; 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(tname.equals("user"))
        {
        Menu  m =new Menu("user");
        m.setVisible(true);
        dispose();
        }
        else if(tname.equals("jubli")){
        Menu  m =new Menu("jubli");
        m.setVisible(true);
        dispose();}
   
    }//GEN-LAST:event_jButton2ActionPerformed
   

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
            // TODO add your handling code here:
    
     try{
        PreparedStatement ps;
        ResultSet rs=null;
        Connection con=  SConnection.getcon();
        
         ps=con.prepareStatement("Insert into feedback(ticket_id,rating,feedback_desc) value(?,?,?)"); 
         
         ps.setString (1,jTextField1.getText());
         ps.setString (2,""+star);
         ps.setString (3,jTextArea2.getText());

         ps.executeUpdate();
         
         JOptionPane.showMessageDialog(this,"Reviewed Successfully");
         jTextField1.setText("");
         jTextArea2.setText("");
          s1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png")));
            s2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png")));
            s3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png")));
            s4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png")));
            s5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/rs(1).png")));
            star=0;
 
         }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(null,e);
         }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:

        if (pos==0)
        {
            lead.setText("BackEnd Developer");
            name.setText("Harsh Kumar");
            emal.setText("Email  : cs211026@dsu.com");
            pho.setText("Phone : +923343241741");
            img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/harsh.jpeg")));
        }
        if(pos==1)
        {
            lead.setText("Code Analyst");
            name.setText("Ahsan Adil");
            emal.setText("Email  : ahsanad@dsu.com");
            pho.setText("Phone : +923316067304");
            img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/ahsan.jpeg")));
        }
        if(pos==2)
        {
            lead.setText("FrontEnd Developer");
            name.setText("Soojal Kumar");
            emal.setText("Email : 1plus2isequalto3@dsu.com");
            pho.setText("Phone : +923362747628");
            img.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gallery/jubli.png")));
            pos=-1;
        }

        pos++;

    }//GEN-LAST:event_jLabel8MouseClicked


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
         try {
    UIManager.setLookAndFeel( new FlatDarkLaf() );
} catch( Exception ex ) {
    System.err.println( "Failed to initialize LaF" );
}
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserFeedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel emal;
    private javax.swing.JLabel img;
    public javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lead;
    private javax.swing.JLabel lead1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel pho;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private javax.swing.JLabel s5;
    // End of variables declaration//GEN-END:variables
}
